---
- name: "update & upgrade packages."
  become: true
  apt:
    update_cache: "yes"
    upgrade: "yes"

- name: "install nodejs and npm."
  become: true
  apt:
    name: ["nodejs", "npm"]

- name: "install n"
  become: true
  npm:
    name: n
    global: yes

- name: "install our node version"
  become: true
  shell: n 13.8.0

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
