---
  - name: "copy backend"
    become: yes
    synchronize:
      src: ../../backend/
      dest: /home/ubuntu/udapeople
      recursive: true

  - name: "stop anything that might already be running"
    become: true
    command: pm2 stop all
    ignore_errors: true

  - name: "start server"
    become: true
    command: pm2 start "npm run start"
    args:
      chdir: /home/ubuntu/udapeople
